services:
  db:
    image: postgres:14
    container_name: tcatb_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: tcatb
      POSTGRES_PASSWORD: tcatbpass
      POSTGRES_DB: tcatb_dev
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: